# Generated by Django 3.0.8 on 2020-08-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=50)),
                ('duration_ms', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('tempo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('recommended_id_string', models.CharField(max_length=5000)),
                ('based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpmsearchapp.Track')),
                ('tracks', models.ManyToManyField(related_name='tracks', to='bpmsearchapp.Track')),
            ],
        ),
    ]
